### ISSUE TITLE
Home Screen Details Not Showing Up

### ISSUE THREAD

**Issue by lancelarsen** [LanceMcCarthy/MvpApi#21]
Great app!  The issue I'm seeing is that it's not downloading (or at least not displaying) the details of the items on the Home page.  It's connecting -- and displaying the "XX of XX" in the upper right hand corner -- but nothing in the details.  To confirm it's connected - it has all the correct info on my "Profile Page" and I can add items that show up on the MVP website - so kudos on those.  Ping me at lance@lancelarsen.com if you want to discuss / view the issue.

![image](https://user-images.githubusercontent.com/4459877/37532790-048669cc-290e-11e8-8870-29afa606c6d1.png)

**Comment by LanceMcCarthy** [comment]
Hmm, what happens if you click the Multi-Select button in the AppBar and then click around in the body of the DataGrid? 

Do you see selection boxes around empty items or does nothing get selected?

If you do see boxes, and selecting individual ones brings you to an empty details page, it's possibly a DataContext problem (might be failing to deserialize).

I'll add in some diagnostics & logging in the next update so that you can share out a log of the deserialization errors.

**Comment by lancelarsen** [comment]
No select boxes -- suspect your suspicion on deserialization is a likely the issue... some odd character or something else is likely choking up the works.  Could just include another info page that will display errors, messages, etc.  Thx man.

**Comment by LanceMcCarthy** [comment]
I [catch the exception there](https://github.com/LanceMcCarthy/MvpApi/blob/3d786aa9afee4e2f9ef0cf1a19b1451bebaf6f91/MvpApi.Uwp/ViewModels/HomePageViewModel.cs#L88) so that the app doesn't crash, but didn't have time for a proper popup & "send error to developer" message for this initial beta. 

I have already written that code (in my other apps), so it will be trivial to add it this one.

Thank you for reporting this!

**Comment by lancelarsen** [comment]
My pleasure - thanks for making a very nice app!  Super slick... :)

//Lance Larsen | www.lancelarsen.com | @lancelarsen
<https://twitter.com/lancelarsen> | 608.31LANCE
//Microsoft MVP | LanceLarsenMVP <http://bit.ly/LanceLarsenMVP>
//HoloSoft | www.holosoft.net <http://holosoft.net/> | @holosoftnet
<https://twitter.com/holosoftnet> | www.facebook.com/holosoft.net
//MADdotNET President | www.maddotnet.com | @maddotnet
<https://twitter.com/maddotnet>

[image: id:image001.png@01D325A2.F505BD00] <http://bit.ly/LanceLarsenMVP>

**Comment by lancelarsen** [comment]
FYI... http://lancelarsen.com/windows-store-mvp-companion/ :)

**Comment by LanceMcCarthy** [comment]
I'm pushing out an update tonight that has a few things that might help:

1 - Exception logging (you'll be able to report an exception to me via email in two clicks)
2 - Batch Size setting feature (you can set it to 25, default was 50 which was higher than the 44)
2 - Manual Refresh button

See the commit history for the work I've got in this update.

**Comment by lancelarsen** [comment]
Whatever you changed -- that build displays everything now... rock on @otherLance :)

**Comment by LanceMcCarthy** [comment]
Fixed in v1. 3.

(subject for reopening if issue arises again)
