### ISSUE TITLE
Not pulling existing items through

### ISSUE THREAD

**Issue by JasonWynn** [LanceMcCarthy/MvpApi#43]
Hello,
I can see that the Home Page displays my items submitted but doesn't show line to by line items within the actual displays.  I can refresh and try to filter but nothing seems to show, however in the upper right-hand corner I can see that the items are being pulled.  In addition, I can submit items fine.

**Comment by LanceMcCarthy** [comment]
Hi Jason!

I'm not sure exactly what you mean by "doesn't show line to by line items within the actual displays"

What happens if you set the BatchSize to 25 instead of the default 50 (find this setting under the wrench icon in the appbar)

**Comment by JasonWynn** [comment]
I’ve shut down while its Story time for the little people, but I’ll try to get a screen grab for you in a minute.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by JasonWynn** [comment]
Works perfectly on 25 rather than 50, thank you.

Odd how that works, should it do that?  Or should it display on 50+?

**Comment by LanceMcCarthy** [comment]
I'm tracking an issue where if the batch number is lower than your total number of contributions, it's not parsing the result correctly.

The same also happens if you have a large amount (say 285) and you get to the last set of items that is lower than the batch number (items 275-285), they don't appear either.

I'll be working on that as soon as I finish a higher priority bug (some profile photos are not decoding from Base64 correctly)

**Comment by LanceMcCarthy** [comment]
Circling back to this after discovering an issue with the API, it's not loading any contributions older than 2016.  This causes a bad problem with paging if you have been an MVP for longer than a couple years because the `TotalContributions` number the API returns is never the total number of items it returns.

The only solution I have at this point is to fetch everything, and rely on UI Virtualization for smooth operation. This will solve everyone's problem, but will take a couple seconds longer to load the DataGrid.

This will be in the 1.8.2 update coming today or tomorrow.

**Comment by JasonWynn** [comment]
Lance, you do realise you’re allowed to have time off mate? 😊

On 26 Dec 2018, at 17:06, Lance McCarthy <notifications@github.com<mailto:notifications@github.com>> wrote:


Circling back to this after discovering an issue with the API, it's not loading any contributions older than 2016. This causes a bad problem with paging if you have been an MVP for longer than a couple years because the TotalContributions number the API returns is never the total number of items it returns.

The only solution I have at this point is to fetch everything, and rely on UI Virtualization for smooth operation. This will solve everyone's problem, but will take a couple seconds longer to load the DataGrid.

This will be in the 1.8.2 update coming today or tomorrow.
