### ISSUE TITLE
Windows 10 - App won't get past login

### ISSUE THREAD

**Issue by wsmelton** [LanceMcCarthy/MvpApi#50]
Fresh install from Windows Store, opened the app and entered my email/password for my MVP profile but the app just continues to prompt:
![image](https://user-images.githubusercontent.com/11204251/46125095-34ad9080-c1ed-11e8-9e58-b5482240fbc0.png)

I'm not able to get past this prompt. Clicking no or yes return the same result, prompt just reappears. I went into app settings and reset the app, same result. Uninstall and reinstall, same result.

**Comment by LanceMcCarthy** [comment]
Thanks for reporting this. Let me build you an APPX with the latest bit today that you can side load.

Another reason for the issue is if the email address you use for portal is also an O365 account (or any AD FS), im rrying to find a solution for these use cases but it seems only the MVP API folks can fix it by allowing multitenent

**Comment by wsmelton** [comment]
I'm using an Outlook.com email address.

**Comment by LanceMcCarthy** [comment]
I've built you a custom release. Download the attached file and take the following steps:

1 - Uninstall the current version
2 - Download this ZIP [MVPCompaion_InternalBuild.zip](https://github.com/LanceMcCarthy/MvpApi/files/2425802/MVPCompaion_InternalBuild.zip)
3 - Right click on the zip file, select "Properties", click the "unblock" checkbox and then OK
4 - Unzip the folder
5 - Right click on the ps1 file and select "run with Powershell"

This will open a command prompt asking you if it's okay to install this app. follow the prompts and it will complete installation.

6 - You'll find the app in your Start menu, go ahead and run it.

You should see this:

![image](https://user-images.githubusercontent.com/3520532/46172885-b1cf1900-c272-11e8-9983-8013ef61f392.png)

**Comment by LanceMcCarthy** [comment]
@wsmelton I published an update to the store, v1.6. Can you let me know if you still have the issue with that release?

**Comment by wsmelton** [comment]
Closing and reopening does not fix it and I do not get prompted to login anymore. I also receive this every time I open the app:

![image](https://user-images.githubusercontent.com/11204251/46572862-8921e000-c952-11e8-82db-2fc8a428e8b2.png)

**Comment by wsmelton** [comment]
Trying to click on the login options both give the same decoding failed error.

**Comment by LanceMcCarthy** [comment]
The error message itself "Image Decoding Failed" is a bit wrong because of the fail fall through (I'm redesigning this as we speak). If you click "Send error and copy base 64", you'll get the actual error code form the API in your clipboard.

It most likely says something like "404 usr not found" or similar.


To erase the local state and start over, uninstall the app and reinstall. This will give the 'Local State' persistence a clean slate and force you to sign back in and get a new access token

**Comment by wsmelton** [comment]
Yeah it returns: ```{ "statusCode": 404, "message": "Resource not found" }```

**Comment by wsmelton** [comment]
Uninstall/reinstall has no effect. The error won't allow the login prompt to show up.

**Comment by LanceMcCarthy** [comment]
Thanks, I'm investigating this now.

What happens if you use the Logout/Login button on the profile page?

**Comment by wsmelton** [comment]
There isn't one...
![image](https://user-images.githubusercontent.com/11204251/46573338-5e875580-c959-11e8-9135-e977d7835e8e.png)

**Comment by wsmelton** [comment]
Truthfully I can't do much of anything, clicking around causes that decoding failure to show up and it just continues to reload.

Just to note I'm still on 1803 for Windows 10, the 1809 update has not hit my machine just yet.
